apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neuroedge.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "neuroedge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "neuroedge.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "neuroedge.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: {{ include "neuroedge.fullname" . }}-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "neuroedge.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
---
{{- if .Values.simulator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neuroedge.fullname" . }}-sim
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.simulator.replicas }}
  selector:
    matchLabels:
      app: neuroedge-sim
  template:
    metadata:
      labels:
        app: neuroedge-sim
    spec:
      containers:
        - name: sim
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["python", "edge/iot_sim/simulator.py"]
          env:
            - name: API_BASE
              value: "http://{{ include "neuroedge.fullname" . }}-svc"
          resources:
            {{- toYaml .Values.simulator.resources | nindent 12 }}
{{- end }}
